---

- name: Upgrade pip
  pip: name=pip version="{{ pip_version }}" virtualenv={{ venv }}

- name: Install numpy
  pip: name=numpy version="{{ numpy_version }}" virtualenv={{ venv }}

- name: Install Jupyter
  pip: name=jupyter version="{{ jupyter_version }}" virtualenv={{ venv }}

- name: Install matplotlib
  pip: name=matplotlib version="{{ matplotlib_version }}" virtualenv={{ venv }}

#Note: using the BBP version of DEAP, as it includes the updated IBEA tools
- name: Install deap
  pip: name='git+https://github.com/BlueBrain/deap#egg=deap' virtualenv={{ venv }}

- name: Install efel
  pip: name=efel version="{{ efel_version }}" virtualenv={{ venv }}

- name: Install scoop
  pip: name=scoop version="{{ scoop_version }}" virtualenv={{ venv }}

#Use the latest version
- name: Install BluePyOpt
  pip: name=bluepyopt virtualenv={{ venv }}

- name: Add virtualenv to setup.sh file
  lineinfile:
    dest="{{ workspace }}/setup.sh"
    create=yes
    line="source {{ venv }}/bin/activate"

- name: Install ssh key
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', 'id_rsa.tmp') }}"
  when: "{{ using_headnode }}"
