# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "head" do |inventory|
        inventory.vm.box = "ubuntu/trusty64"
        inventory.vm.network "private_network", ip: "192.168.61.10"
    end

    config.vm.define "worker0" do |inventory|
        inventory.vm.box = "ubuntu/trusty64"
        inventory.vm.network "private_network", ip: "192.168.61.20"
    end
    config.vm.define "worker1" do |inventory|
        inventory.vm.box = "ubuntu/trusty64"
        inventory.vm.network "private_network", ip: "192.168.61.21"
    end
    config.vm.define "worker2" do |inventory|
        inventory.vm.box = "ubuntu/trusty64"
        inventory.vm.network "private_network", ip: "192.168.61.22"
    end
end
